# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Python
  items:
    - label: 'requirements'
      link: 'python/requirements'
- label: Testing
  items:
    - label: 'E2E vs Integration'
      link: '/Testing/e2e-vs-integration'
- label: More
  items:
    - label: 'Github'
      link: https://github.com/ccp92/wiki
    - label: 'Twitter'
      link: https://twitter.com/ccp92
