# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Python
  items:
    - label: 'Django'
      link: '/python/django'
    - label: 'requirements'
      link: 'python/requirements'
- label: More
  items:
    - label: 'Github'
      link: https://github.com/ccp92/wiki
    - label: 'Twitter'
      link: https://twitter.com/ccp92
